/**
 * Self-Healing Code Analysis for Active Operator
 *
 * Scans the codebase for TypeScript errors and uses LLM to suggest fixes.
 * Creates proposals that the user can review and approve.
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { systemPaths, ROOT, getProfilePaths } from '../paths.js';
import { audit } from '../audit.js';
import { callLLM } from '../model-router.js';
import { randomUUID } from 'crypto';

/**
 * A TypeScript error from tsc output.
 */
export interface TSError {
  file: string;
  line: number;
  column: number;
  code: string;
  message: string;
}

/**
 * A fix proposal generated by the LLM.
 */
export interface FixProposal {
  id: string;
  createdAt: string;
  error: TSError;
  analysis: string;
  suggestedFix: string;
  diff?: string;
  confidence: 'high' | 'medium' | 'low';
  status: 'pending' | 'approved' | 'rejected' | 'applied';
}

/**
 * Parse tsc --noEmit output into structured errors.
 */
export function parseTscOutput(output: string): TSError[] {
  const errors: TSError[] = [];
  const lines = output.split('\n');

  // Pattern: file(line,col): error TSxxxx: message
  const errorPattern = /^(.+?)\((\d+),(\d+)\):\s*error\s+(TS\d+):\s*(.+)$/;

  for (const line of lines) {
    const match = line.match(errorPattern);
    if (match) {
      errors.push({
        file: match[1],
        line: parseInt(match[2], 10),
        column: parseInt(match[3], 10),
        code: match[4],
        message: match[5],
      });
    }
  }

  return errors;
}

/**
 * Run TypeScript type checking on the codebase.
 * Returns list of errors found.
 */
export function runTypeCheck(): TSError[] {
  try {
    // Run tsc in packages/core (main codebase)
    const cwd = path.join(ROOT, 'packages', 'core');

    // Use npx to run tsc with noEmit
    const result = execSync('npx tsc --noEmit 2>&1', {
      cwd,
      encoding: 'utf-8',
      timeout: 120000, // 2 minute timeout
      maxBuffer: 10 * 1024 * 1024, // 10MB buffer
    });

    // If we get here without error, there are no TS errors
    return [];
  } catch (error: any) {
    // tsc exits with non-zero when there are errors
    // The output is in error.stdout
    const output = error.stdout || error.message || '';
    return parseTscOutput(output);
  }
}

/**
 * Get context around an error location.
 */
function getErrorContext(filePath: string, line: number, contextLines: number = 5): string {
  try {
    const fullPath = path.isAbsolute(filePath) ? filePath : path.join(ROOT, filePath);
    if (!fs.existsSync(fullPath)) {
      return `[File not found: ${filePath}]`;
    }

    const content = fs.readFileSync(fullPath, 'utf-8');
    const lines = content.split('\n');

    const startLine = Math.max(0, line - contextLines - 1);
    const endLine = Math.min(lines.length, line + contextLines);

    const contextSnippet = lines
      .slice(startLine, endLine)
      .map((l, i) => {
        const lineNum = startLine + i + 1;
        const marker = lineNum === line ? '>>>' : '   ';
        return `${marker} ${lineNum.toString().padStart(4)}: ${l}`;
      })
      .join('\n');

    return contextSnippet;
  } catch {
    return `[Error reading file: ${filePath}]`;
  }
}

/**
 * Analyze an error and generate a fix proposal using LLM.
 */
export async function analyzeError(error: TSError, username: string): Promise<FixProposal> {
  const context = getErrorContext(error.file, error.line);

  const messages = [
    {
      role: 'system' as const,
      content: `You are a TypeScript expert analyzing a compile error. Your job is to:
1. Understand what the error means
2. Analyze the code context
3. Suggest a specific fix

Be concise and practical. Focus on the most likely fix.`,
    },
    {
      role: 'user' as const,
      content: `TypeScript Error:
File: ${error.file}
Line: ${error.line}, Column: ${error.column}
Code: ${error.code}
Message: ${error.message}

Code Context:
\`\`\`typescript
${context}
\`\`\`

Please analyze this error and suggest a fix. Respond in JSON format:
{
  "analysis": "Brief explanation of what's wrong",
  "suggestedFix": "The specific code change to make",
  "diff": "A simple before/after showing the change",
  "confidence": "high" | "medium" | "low"
}`,
    },
  ];

  try {
    const response = await callLLM({
      role: 'orchestrator',
      messages,
      userId: username,
      options: {
        maxTokens: 1024,
        temperature: 0.2,
      },
    });

    // Parse the response
    const jsonMatch = response.content.match(/\{[\s\S]*\}/);
    let analysis = 'Unable to analyze';
    let suggestedFix = 'Manual review required';
    let diff: string | undefined;
    let confidence: 'high' | 'medium' | 'low' = 'low';

    if (jsonMatch) {
      try {
        const parsed = JSON.parse(jsonMatch[0]);
        analysis = parsed.analysis || analysis;
        suggestedFix = parsed.suggestedFix || suggestedFix;
        diff = parsed.diff;
        confidence = parsed.confidence || confidence;
      } catch {
        // Use defaults
      }
    }

    return {
      id: `fix-${randomUUID().slice(0, 8)}`,
      createdAt: new Date().toISOString(),
      error,
      analysis,
      suggestedFix,
      diff,
      confidence,
      status: 'pending',
    };
  } catch (err) {
    return {
      id: `fix-${randomUUID().slice(0, 8)}`,
      createdAt: new Date().toISOString(),
      error,
      analysis: `Error analyzing: ${(err as Error).message}`,
      suggestedFix: 'Manual review required',
      confidence: 'low',
      status: 'pending',
    };
  }
}

/**
 * Save a fix proposal to disk.
 */
export function saveProposal(proposal: FixProposal, username: string): string {
  const profilePaths = getProfilePaths(username);
  const proposalsDir = path.join(profilePaths.state, 'code-proposals');

  if (!fs.existsSync(proposalsDir)) {
    fs.mkdirSync(proposalsDir, { recursive: true });
  }

  const filePath = path.join(proposalsDir, `${proposal.id}.json`);
  fs.writeFileSync(filePath, JSON.stringify(proposal, null, 2));

  return filePath;
}

/**
 * Load all pending proposals for a user.
 */
export function loadPendingProposals(username: string): FixProposal[] {
  const profilePaths = getProfilePaths(username);
  const proposalsDir = path.join(profilePaths.state, 'code-proposals');

  if (!fs.existsSync(proposalsDir)) {
    return [];
  }

  const proposals: FixProposal[] = [];
  const files = fs.readdirSync(proposalsDir).filter((f) => f.endsWith('.json'));

  for (const file of files) {
    try {
      const content = fs.readFileSync(path.join(proposalsDir, file), 'utf-8');
      const proposal = JSON.parse(content) as FixProposal;
      if (proposal.status === 'pending') {
        proposals.push(proposal);
      }
    } catch {
      // Skip malformed files
    }
  }

  return proposals.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/**
 * Update a proposal's status.
 */
export function updateProposalStatus(
  proposalId: string,
  status: 'approved' | 'rejected' | 'applied',
  username: string
): boolean {
  const profilePaths = getProfilePaths(username);
  const proposalsDir = path.join(profilePaths.state, 'code-proposals');
  const filePath = path.join(proposalsDir, `${proposalId}.json`);

  if (!fs.existsSync(filePath)) {
    return false;
  }

  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const proposal = JSON.parse(content) as FixProposal;
    proposal.status = status;
    fs.writeFileSync(filePath, JSON.stringify(proposal, null, 2));

    audit({
      category: 'system',
      level: 'info',
      event: 'code_proposal_status_changed',
      actor: username,
      details: {
        proposalId,
        newStatus: status,
        file: proposal.error.file,
        errorCode: proposal.error.code,
      },
    });

    return true;
  } catch {
    return false;
  }
}

/**
 * Run full self-healing analysis.
 * Returns the number of new proposals created.
 */
export async function runSelfHealing(
  username: string,
  maxErrors: number = 5
): Promise<{
  errorsFound: number;
  proposalsCreated: number;
  proposals: FixProposal[];
}> {
  console.log('[self-healing] Running TypeScript type check...');

  const errors = runTypeCheck();

  if (errors.length === 0) {
    console.log('[self-healing] No TypeScript errors found');
    return { errorsFound: 0, proposalsCreated: 0, proposals: [] };
  }

  console.log(`[self-healing] Found ${errors.length} TypeScript errors`);

  // Limit to maxErrors to avoid overwhelming the system
  const errorsToAnalyze = errors.slice(0, maxErrors);
  const proposals: FixProposal[] = [];

  for (const error of errorsToAnalyze) {
    console.log(`[self-healing] Analyzing: ${error.file}:${error.line} - ${error.code}`);

    try {
      const proposal = await analyzeError(error, username);
      proposals.push(proposal);
      saveProposal(proposal, username);
    } catch (err) {
      console.error(`[self-healing] Error analyzing ${error.file}:`, err);
    }
  }

  audit({
    category: 'system',
    level: 'info',
    event: 'self_healing_analysis_complete',
    actor: 'active-operator',
    details: {
      errorsFound: errors.length,
      errorsAnalyzed: errorsToAnalyze.length,
      proposalsCreated: proposals.length,
      username,
    },
  });

  console.log(`[self-healing] Created ${proposals.length} fix proposals`);

  return {
    errorsFound: errors.length,
    proposalsCreated: proposals.length,
    proposals,
  };
}

/**
 * Get error count without full analysis (for system state).
 */
export function getErrorCount(): number {
  const errors = runTypeCheck();
  return errors.length;
}

/**
 * Context provided by Big Brother for guided self-healing.
 */
export interface BigBrotherHealingContext {
  recentErrors: TSError[];
  scratchpadContext: string;
  bigBrotherSuggestions: string[];
  triggerReason: 'errors' | 'stuck' | 'periodic';
  cycleNumber: number;
}

/**
 * Result of Big Brother guided self-healing.
 */
export interface BigBrotherHealingResult {
  success: boolean;
  analysisRequested: boolean;
  proposalsCreated: number;
  suggestionsApplied: string[];
  errorMessage?: string;
}

/**
 * Trigger self-healing with Big Brother's guidance.
 *
 * This function is called when the Big Brother reviewer detects issues
 * (repeated errors, stuck state, or periodic review). It:
 * 1. Analyzes the error context with Big Brother's suggestions
 * 2. Runs targeted self-healing on the most relevant errors
 * 3. Returns results for logging and scratchpad updates
 */
export async function triggerBigBrotherHealing(
  username: string,
  context: BigBrotherHealingContext
): Promise<BigBrotherHealingResult> {
  const suggestionsApplied: string[] = [];

  audit({
    category: 'system',
    level: 'info',
    event: 'big_brother_healing_triggered',
    actor: 'big-brother-reviewer',
    details: {
      username,
      triggerReason: context.triggerReason,
      cycleNumber: context.cycleNumber,
      errorCount: context.recentErrors.length,
      suggestionCount: context.bigBrotherSuggestions.length,
    },
  });

  try {
    // If Big Brother provided specific suggestions, log them
    if (context.bigBrotherSuggestions.length > 0) {
      console.log('[big-brother-healing] Received suggestions:', context.bigBrotherSuggestions);

      // Check for specific actionable suggestions
      for (const suggestion of context.bigBrotherSuggestions) {
        const lower = suggestion.toLowerCase();

        if (lower.includes('run type check') || lower.includes('run tsc')) {
          console.log('[big-brother-healing] Acting on: run type check');
          suggestionsApplied.push('run_type_check');
        }

        if (lower.includes('analyze error') || lower.includes('fix error')) {
          console.log('[big-brother-healing] Acting on: analyze errors');
          suggestionsApplied.push('analyze_errors');
        }

        if (lower.includes('clear scratchpad') || lower.includes('reset')) {
          console.log('[big-brother-healing] Suggestion noted: clear scratchpad');
          suggestionsApplied.push('clear_scratchpad_suggested');
        }
      }
    }

    // If we have recent TypeScript errors, run self-healing on them
    if (context.recentErrors.length > 0) {
      console.log(`[big-brother-healing] Analyzing ${context.recentErrors.length} recent errors`);

      // Run self-healing with guidance from Big Brother
      const healingResult = await runSelfHealing(username, context.recentErrors.length);

      audit({
        category: 'system',
        level: 'info',
        event: 'big_brother_healing_complete',
        actor: 'big-brother-reviewer',
        details: {
          username,
          triggerReason: context.triggerReason,
          proposalsCreated: healingResult.proposalsCreated,
          suggestionsApplied,
        },
      });

      return {
        success: true,
        analysisRequested: true,
        proposalsCreated: healingResult.proposalsCreated,
        suggestionsApplied,
      };
    }

    // No errors to analyze, but log the review
    console.log('[big-brother-healing] No TypeScript errors to analyze');

    return {
      success: true,
      analysisRequested: false,
      proposalsCreated: 0,
      suggestionsApplied,
    };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : 'Unknown error';

    audit({
      category: 'system',
      level: 'error',
      event: 'big_brother_healing_failed',
      actor: 'big-brother-reviewer',
      details: {
        username,
        triggerReason: context.triggerReason,
        error: errorMessage,
      },
    });

    return {
      success: false,
      analysisRequested: false,
      proposalsCreated: 0,
      suggestionsApplied,
      errorMessage,
    };
  }
}
