/**
 * Self-Healing Code Analysis for Active Operator
 *
 * Scans the codebase for TypeScript errors and uses LLM to suggest fixes.
 * Creates proposals that the user can review and approve.
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { systemPaths, ROOT, getProfilePaths } from '../paths.js';
import { audit } from '../audit.js';
import { randomUUID } from 'crypto';
import { getUserContext } from '../context.js';
import {
  cognitiveGraphPath,
  loadGraphFile,
  requireGraphNodeOutput,
  runGraph,
} from '../graph-runtime.js';
import type { SelfHealingAnalysis } from '../nodes/active-operator/self-healing-analysis.node.js';

/**
 * A TypeScript error from tsc output.
 */
export interface TSError {
  file: string;
  line: number;
  column: number;
  code: string;
  message: string;
}

/**
 * A fix proposal generated by the LLM.
 */
export interface FixProposal {
  id: string;
  createdAt: string;
  error: TSError;
  analysis: string;
  suggestedFix: string;
  diff?: string;
  confidence: 'high' | 'medium' | 'low';
  status: 'pending' | 'approved' | 'rejected' | 'applied';
}

/**
 * Parse tsc --noEmit output into structured errors.
 */
export function parseTscOutput(output: string): TSError[] {
  const errors: TSError[] = [];
  const lines = output.split('\n');

  // Pattern: file(line,col): error TSxxxx: message
  const errorPattern = /^(.+?)\((\d+),(\d+)\):\s*error\s+(TS\d+):\s*(.+)$/;

  for (const line of lines) {
    const match = line.match(errorPattern);
    if (match) {
      errors.push({
        file: match[1],
        line: parseInt(match[2], 10),
        column: parseInt(match[3], 10),
        code: match[4],
        message: match[5],
      });
    }
  }

  return errors;
}

/**
 * Run TypeScript type checking on the codebase.
 * Returns list of errors found.
 */
export function runTypeCheck(): TSError[] {
  try {
    // Run tsc in packages/core (main codebase)
    const cwd = path.join(ROOT, 'packages', 'core');

    // Use npx to run tsc with noEmit
    const result = execSync('npx tsc --noEmit 2>&1', {
      cwd,
      encoding: 'utf-8',
      timeout: 120000, // 2 minute timeout
      maxBuffer: 10 * 1024 * 1024, // 10MB buffer
    });

    // If we get here without error, there are no TS errors
    return [];
  } catch (error: any) {
    // tsc exits with non-zero when there are errors
    // The output is in error.stdout
    const output = error.stdout || error.message || '';
    return parseTscOutput(output);
  }
}

/**
 * Get context around an error location.
 */
function getErrorContext(filePath: string, line: number, contextLines: number = 5): string {
  try {
    const fullPath = path.isAbsolute(filePath) ? filePath : path.join(ROOT, filePath);
    if (!fs.existsSync(fullPath)) {
      return `[File not found: ${filePath}]`;
    }

    const content = fs.readFileSync(fullPath, 'utf-8');
    const lines = content.split('\n');

    const startLine = Math.max(0, line - contextLines - 1);
    const endLine = Math.min(lines.length, line + contextLines);

    const contextSnippet = lines
      .slice(startLine, endLine)
      .map((l, i) => {
        const lineNum = startLine + i + 1;
        const marker = lineNum === line ? '>>>' : '   ';
        return `${marker} ${lineNum.toString().padStart(4)}: ${l}`;
      })
      .join('\n');

    return contextSnippet;
  } catch {
    return `[Error reading file: ${filePath}]`;
  }
}

/**
 * Analyze an error and generate a fix proposal using LLM.
 */
export async function analyzeError(
  error: TSError,
  username: string,
  signal?: AbortSignal,
): Promise<FixProposal> {
  const activeUser = getUserContext();
  if (!activeUser || (activeUser.username !== username && activeUser.activeProfile !== username)) {
    throw new Error(`Self-healing analysis requires an authenticated context for ${username}`);
  }
  const loaded = await loadGraphFile(cognitiveGraphPath('self-healing-analysis.json'), {
    cacheKey: 'self-healing-analysis',
    logPrefix: '[self-healing]',
  });
  if (!loaded) throw new Error('Self-healing analysis graph is unavailable');
  const state = await runGraph({
    graph: loaded.graph,
    signal,
    context: {
      userId: activeUser.userId,
      username,
      typeScriptError: error,
      errorContext: getErrorContext(error.file, error.line),
      cognitiveMode: 'agent',
      allowMemoryWrites: false,
      recordPersonaMemory: false,
      abortSignal: signal,
    },
  });
  if (state.status !== 'completed') {
    throw new Error(`Self-healing analysis graph ended with status ${state.status}`);
  }
  const output = requireGraphNodeOutput(state, 'self_healing_analysis');
  const analysis = output.result as SelfHealingAnalysis | undefined;
  if (!analysis?.analysis || !analysis.suggestedFix
    || !['high', 'medium', 'low'].includes(analysis.confidence)) {
    throw new Error('Self-healing analysis graph returned an invalid proposal');
  }
  return {
    id: `fix-${randomUUID().slice(0, 8)}`,
    createdAt: new Date().toISOString(),
    error,
    ...analysis,
    status: 'pending',
  };
}

/**
 * Save a fix proposal to disk.
 */
export function saveProposal(proposal: FixProposal, username: string): string {
  const profilePaths = getProfilePaths(username);
  const proposalsDir = path.join(profilePaths.state, 'code-proposals');

  if (!fs.existsSync(proposalsDir)) {
    fs.mkdirSync(proposalsDir, { recursive: true });
  }

  const filePath = path.join(proposalsDir, `${proposal.id}.json`);
  fs.writeFileSync(filePath, JSON.stringify(proposal, null, 2));

  return filePath;
}

/**
 * Load all pending proposals for a user.
 */
export function loadPendingProposals(username: string): FixProposal[] {
  const profilePaths = getProfilePaths(username);
  const proposalsDir = path.join(profilePaths.state, 'code-proposals');

  if (!fs.existsSync(proposalsDir)) {
    return [];
  }

  const proposals: FixProposal[] = [];
  const files = fs.readdirSync(proposalsDir).filter((f) => f.endsWith('.json'));

  for (const file of files) {
    try {
      const content = fs.readFileSync(path.join(proposalsDir, file), 'utf-8');
      const proposal = JSON.parse(content) as FixProposal;
      if (proposal.status === 'pending') {
        proposals.push(proposal);
      }
    } catch {
      // Skip malformed files
    }
  }

  return proposals.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/**
 * Update a proposal's status.
 */
export function updateProposalStatus(
  proposalId: string,
  status: 'approved' | 'rejected' | 'applied',
  username: string
): boolean {
  const profilePaths = getProfilePaths(username);
  const proposalsDir = path.join(profilePaths.state, 'code-proposals');
  const filePath = path.join(proposalsDir, `${proposalId}.json`);

  if (!fs.existsSync(filePath)) {
    return false;
  }

  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const proposal = JSON.parse(content) as FixProposal;
    proposal.status = status;
    fs.writeFileSync(filePath, JSON.stringify(proposal, null, 2));

    audit({
      category: 'system',
      level: 'info',
      event: 'code_proposal_status_changed',
      actor: username,
      details: {
        proposalId,
        newStatus: status,
        file: proposal.error.file,
        errorCode: proposal.error.code,
      },
    });

    return true;
  } catch {
    return false;
  }
}

/**
 * Run full self-healing analysis.
 * Returns the number of new proposals created.
 */
export async function runSelfHealing(
  username: string,
  maxErrors: number = 5,
  signal?: AbortSignal,
): Promise<{
  errorsFound: number;
  proposalsCreated: number;
  proposals: FixProposal[];
  errors: string[];
}> {
  if (!Number.isInteger(maxErrors) || maxErrors < 1 || maxErrors > 50) {
    throw new Error('Self-healing maxErrors must be an integer from 1 to 50');
  }
  console.log('[self-healing] Running TypeScript type check...');

  const errors = runTypeCheck();

  if (errors.length === 0) {
    console.log('[self-healing] No TypeScript errors found');
    return { errorsFound: 0, proposalsCreated: 0, proposals: [], errors: [] };
  }

  console.log(`[self-healing] Found ${errors.length} TypeScript errors`);

  // Limit to maxErrors to avoid overwhelming the system
  const errorsToAnalyze = errors.slice(0, maxErrors);
  const proposals: FixProposal[] = [];
  const analysisErrors: string[] = [];

  for (const error of errorsToAnalyze) {
    console.log(`[self-healing] Analyzing: ${error.file}:${error.line} - ${error.code}`);

    try {
      const proposal = await analyzeError(error, username, signal);
      proposals.push(proposal);
      saveProposal(proposal, username);
    } catch (err) {
      console.error(`[self-healing] Error analyzing ${error.file}:`, err);
      analysisErrors.push(`${error.file}:${error.line}: ${(err as Error).message}`);
    }
  }

  audit({
    category: 'system',
    level: analysisErrors.length > 0 ? 'warn' : 'info',
    event: 'self_healing_analysis_complete',
    actor: 'active-operator',
    details: {
      errorsFound: errors.length,
      errorsAnalyzed: errorsToAnalyze.length,
      proposalsCreated: proposals.length,
      username,
    },
  });

  console.log(`[self-healing] Created ${proposals.length} fix proposals`);

  return {
    errorsFound: errors.length,
    proposalsCreated: proposals.length,
    proposals,
    errors: analysisErrors,
  };
}

/**
 * Get error count without full analysis (for system state).
 */
export function getErrorCount(): number {
  const errors = runTypeCheck();
  return errors.length;
}
