#!/bin/bash
#
# Release MetaHuman Mobile APK
#
# This script:
# 1. Auto-increments versionCode (and optionally version string)
# 2. Builds the APK using build-mobile.sh
# 3. Copies APK to apps/mobile/releases/ with correct naming
# 4. Updates version.json for server-side version checks
#
# Usage:
#   ./release-apk.sh              # Auto-increment versionCode only
#   ./release-apk.sh 1.1.0        # Set specific version string
#   ./release-apk.sh --notes "Bug fixes"  # Add release notes
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RN_DIR="$(dirname "$SCRIPT_DIR")"
ROOT_DIR="$RN_DIR/../.."
RELEASES_DIR="$ROOT_DIR/apps/mobile/releases"
VERSION_FILE="$RELEASES_DIR/version.json"

# Parse arguments
NEW_VERSION=""
RELEASE_NOTES=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --notes)
            RELEASE_NOTES="$2"
            shift 2
            ;;
        -*)
            echo "Unknown option: $1"
            exit 1
            ;;
        *)
            NEW_VERSION="$1"
            shift
            ;;
    esac
done

# Ensure releases directory exists
mkdir -p "$RELEASES_DIR"

# Read current version or create default
if [ -f "$VERSION_FILE" ]; then
    CURRENT_VERSION=$(jq -r '.version' "$VERSION_FILE")
    CURRENT_VERSION_CODE=$(jq -r '.versionCode' "$VERSION_FILE")
    CURRENT_NOTES=$(jq -r '.releaseNotes // ""' "$VERSION_FILE")
else
    CURRENT_VERSION="1.0.0"
    CURRENT_VERSION_CODE=0
    CURRENT_NOTES="Initial release"
fi

# Increment versionCode
NEW_VERSION_CODE=$((CURRENT_VERSION_CODE + 1))

# Use provided version or keep current
if [ -z "$NEW_VERSION" ]; then
    NEW_VERSION="$CURRENT_VERSION"
fi

# Use provided notes or generate default
if [ -z "$RELEASE_NOTES" ]; then
    RELEASE_NOTES="Build $NEW_VERSION_CODE - $(date +%Y-%m-%d)"
fi

echo "=========================================="
echo "  MetaHuman Mobile Release"
echo "=========================================="
echo ""
echo "  Current: v$CURRENT_VERSION (code: $CURRENT_VERSION_CODE)"
echo "  New:     v$NEW_VERSION (code: $NEW_VERSION_CODE)"
echo "  Notes:   $RELEASE_NOTES"
echo ""

# Confirm
read -p "Proceed with build? [y/N] " -n 1 -r
echo ""
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

# Update version.json BEFORE build
echo ""
echo "[1/5] Updating version.json..."
cat > "$VERSION_FILE" << EOF
{
  "version": "$NEW_VERSION",
  "versionCode": $NEW_VERSION_CODE,
  "releaseDate": "$(date +%Y-%m-%d)",
  "releaseNotes": "$RELEASE_NOTES",
  "minAndroidVersion": 26,
  "downloadUrl": "/downloads/metahuman-os.apk"
}
EOF
echo "  Updated: $VERSION_FILE"

# Write version to nodejs-project .env (read by handleAppInfo)
echo ""
echo "[2/5] Writing version to mobile .env..."
NODEJS_PROJECT="$RN_DIR/nodejs-assets/nodejs-project"
cat > "$NODEJS_PROJECT/.env" << EOF
# Auto-generated by release-apk.sh - DO NOT EDIT
APP_VERSION=$NEW_VERSION
APP_VERSION_CODE=$NEW_VERSION_CODE
APP_BUILD_DATE=$(date -Iseconds)
METAHUMAN_MOBILE=true
EOF
echo "  Updated: $NODEJS_PROJECT/.env"

# Run the build
echo ""
echo "[3/5] Building APK..."
cd "$SCRIPT_DIR"
./build-mobile.sh

# Find the built APK
APK_SOURCE="$RN_DIR/android/app/build/outputs/apk/debug/app-debug.apk"
if [ ! -f "$APK_SOURCE" ]; then
    echo "Error: APK not found at $APK_SOURCE"
    exit 1
fi

# Copy to releases with version name
APK_VERSIONED="$RELEASES_DIR/metahuman-$NEW_VERSION.apk"
APK_LATEST="$RELEASES_DIR/metahuman-latest.apk"

echo ""
echo "[4/5] Copying APK to releases..."
cp "$APK_SOURCE" "$APK_VERSIONED"
cp "$APK_SOURCE" "$APK_LATEST"
echo "  Copied: $APK_VERSIONED"
echo "  Copied: $APK_LATEST"

# Create symlink for generic download URL
DOWNLOADS_DIR="$ROOT_DIR/apps/site/public/downloads"
mkdir -p "$DOWNLOADS_DIR"
cp "$APK_SOURCE" "$DOWNLOADS_DIR/metahuman-os.apk"
echo "  Copied: $DOWNLOADS_DIR/metahuman-os.apk"

# Get final APK size
APK_SIZE=$(du -h "$APK_VERSIONED" | cut -f1)
APK_SIZE_BYTES=$(stat -c%s "$APK_VERSIONED")

# Update version.json with file size
echo ""
echo "[5/5] Finalizing version.json..."
cat > "$VERSION_FILE" << EOF
{
  "version": "$NEW_VERSION",
  "versionCode": $NEW_VERSION_CODE,
  "releaseDate": "$(date +%Y-%m-%d)",
  "releaseNotes": "$RELEASE_NOTES",
  "minAndroidVersion": 26,
  "fileSize": $APK_SIZE_BYTES,
  "downloadUrl": "/downloads/metahuman-os.apk"
}
EOF

echo ""
echo "=========================================="
echo "  Release Complete!"
echo "=========================================="
echo ""
echo "  Version: $NEW_VERSION (code: $NEW_VERSION_CODE)"
echo "  APK Size: $APK_SIZE"
echo "  Files:"
echo "    - $APK_VERSIONED"
echo "    - $APK_LATEST"
echo "    - $DOWNLOADS_DIR/metahuman-os.apk"
echo "    - $VERSION_FILE"
echo ""
echo "  Mobile devices will see update: v$CURRENT_VERSION → v$NEW_VERSION"
echo ""
echo "  To deploy:"
echo "    1. Restart the web server (./start.sh)"
echo "    2. Mobile app will detect update on next sync"
echo ""
