#!/usr/bin/env tsx
/**
 * Dev Session Helper
 *
 * Creates an authenticated session for development to avoid "anonymous user" errors.
 *
 * Usage:
 *   pnpm tsx scripts/dev-session.ts --username owner
 *   pnpm tsx scripts/dev-session.ts --username greggles
 *
 * This will:
 * 1. Create/update a session in logs/run/sessions.json
 * 2. Output the session cookie value to copy into your browser DevTools
 * 3. Optionally write it to .env.development for automated injection
 */

import { randomBytes } from 'node:crypto';
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { systemPaths } from '@metahuman/core';
import { getUserByUsername } from '@metahuman/core/users';

const args = process.argv.slice(2);
const usernameArg = args.find(arg => arg.startsWith('--username='));
const username = usernameArg ? usernameArg.split('=')[1] : 'greggles';

// Verify user exists
const user = getUserByUsername(username);
if (!user) {
  console.error(`❌ User "${username}" not found. Available users:`);
  try {
    const usersPath = systemPaths.usersDb;
    if (existsSync(usersPath)) {
      const usersData = JSON.parse(readFileSync(usersPath, 'utf-8'));
      const users = usersData.users || [];
      users.forEach((u: any) => console.error(`   - ${u.username} (${u.role})`));
    }
  } catch {}
  process.exit(1);
}

// Generate session token
const sessionId = randomBytes(32).toString('hex');

// Load existing sessions
const sessionsPath = join(systemPaths.run, 'sessions.json');
let sessions: any = { sessions: {} };
if (existsSync(sessionsPath)) {
  try {
    sessions = JSON.parse(readFileSync(sessionsPath, 'utf-8'));
  } catch {
    // Start fresh if corrupted
  }
}

// Create session
const expiresAt = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000); // 30 days
sessions.sessions[sessionId] = {
  userId: user.id,
  username: user.username,
  role: user.role,
  createdAt: new Date().toISOString(),
  expiresAt: expiresAt.toISOString(),
  metadata: {
    source: 'dev-session-helper',
  },
};

// Write sessions file
writeFileSync(sessionsPath, JSON.stringify(sessions, null, 2));

console.log('✅ Dev session created successfully!\n');
console.log('Session Details:');
console.log(`  User: ${user.username} (${user.role})`);
console.log(`  Session ID: ${sessionId}`);
console.log(`  Expires: ${expiresAt.toISOString()}\n`);

console.log('🍪 Copy this cookie value into your browser:\n');
console.log(`  Cookie Name:  mh_session`);
console.log(`  Cookie Value: ${sessionId}\n`);

console.log('📋 Browser DevTools Steps:');
console.log('  1. Open DevTools (F12)');
console.log('  2. Go to Application → Cookies → http://localhost:4321');
console.log('  3. Add a new cookie:');
console.log(`     Name:  mh_session`);
console.log(`     Value: ${sessionId}`);
console.log('  4. Reload the page\n');

// Optionally write to .env.development
const envPath = join(systemPaths.root, '.env.development');
const envContent = `# Auto-generated by dev-session.ts
# Session for user: ${user.username}
# Generated: ${new Date().toISOString()}
MH_DEV_SESSION=${sessionId}
`;

try {
  writeFileSync(envPath, envContent);
  console.log('📝 Session also saved to .env.development');
  console.log('   (Note: You still need to manually set the cookie in your browser)\n');
} catch (error) {
  console.log('⚠️  Could not write to .env.development (not critical)');
}

console.log('✨ Happy developing!');
