/**
 * Curated semantic paraphrases for development cases only.
 *
 * These are system-owned training inputs, not user/profile data. Held-out case
 * ids and instructions must never be added here. Each paraphrase preserves the
 * source case's exact routing decision while changing its linguistic surface.
 */
export const DEVELOPMENT_SEMANTIC_VARIANTS: Readonly<Record<string, readonly string[]>> = {
  'conversation-001': [
    'How is your day going?',
    'How have you been today?',
    'How are things with you today?',
    'Tell me how you are doing today.',
  ],
  'conversation-002': [
    'Tell me a brief joke involving rain.',
    'Give me a quick rainy-day joke.',
    'Can you make a short joke about wet weather?',
    'Share one concise joke about rainfall.',
  ],
  'conversation-003': [
    'Why do tree leaves change color in the fall?',
    'Explain the science behind autumn leaf colors.',
    'What causes leaves to change color during autumn?',
    'Tell me why foliage changes color in the fall.',
  ],
  'conversation-004': [
    'Thanks for your help.',
    'I appreciate the assistance.',
    'Thank you for being helpful.',
    'I am grateful for your help.',
  ],
  'conversation-005': [
    'Compose a two-line poem about being patient.',
    'Write two poetic lines about patience.',
    'Give me a very short, two-line patience poem.',
    'Create a poem about patience using exactly two lines.',
  ],
  'memory-001': [
    'What response-length preference did I save before?',
    'Recall my previously stored preference for answer length.',
    'Which preferred response length is saved for me?',
    'Tell me the answer-length preference I recorded earlier.',
  ],
  'memory-002': [
    'What did we talk about earlier regarding gardening?',
    'Recall our previous gardening discussion.',
    'What was said in our earlier conversation about gardening?',
    'Remind me what we discussed before about gardening.',
  ],
  'memory-004': [
    'Retrieve your most recently stored reflection on learning.',
    'What was your last saved learning reflection?',
    'Recall the latest reflection you stored about learning.',
    'Tell me your previous stored reflection concerning learning.',
  ],
  'memory-006': [
    'What action was saved for the previous shelf test?',
    'Recall the recorded action from the earlier shelf test.',
    'Which shelf-test action did you store before?',
    'Tell me the action logged for that past shelf test.',
  ],
  'state-001': [
    'What battery percentage do you have right now?',
    'Report your present battery level.',
    'How much battery remains currently?',
    'Tell me your live battery charge.',
  ],
  'state-002': [
    'Are you currently online?',
    'Report whether your connection is active now.',
    'What is your present connection status?',
    'Are you connected at this moment?',
  ],
  'state-004': [
    'What is your current activity?',
    'Report your present activity mode.',
    'Which activity state are you currently reporting?',
    'Tell me your live activity status.',
  ],
  'state-005': [
    'Is your camera currently able to take a picture?',
    'Report whether visual capture is available right now.',
    'Can the camera acquire an image at this moment?',
    'Is current image capture supported?',
  ],
  'state-006': [
    'Give me your current battery and connection status.',
    'Report both your live connection and remaining charge.',
    'What are your present connectivity and battery readings?',
    'Tell me whether you are connected and how much battery remains.',
  ],
  'fresh-vision-001': [
    'Describe what is visible right now.',
    'What can you see in the current view?',
    'Tell me what the latest camera image shows.',
    'Describe the scene in front of you now.',
  ],
  'fresh-vision-002': [
    'Read the text on the label in the current frame.',
    'What does the visible label say right now?',
    'Transcribe the label shown in the latest image.',
    'Tell me the words visible on the current label.',
  ],
  'fresh-vision-004': [
    'How many red blocks are visible in the latest image?',
    'Count the red blocks shown in the current frame.',
    'Tell me the number of red blocks you can presently see.',
    'Using the image just received, count every red block.',
  ],
  'fresh-vision-005': [
    'Does the fresh camera image show an open cabinet door?',
    'Check the current frame and tell me whether the cabinet is open.',
    'From the latest image, is that cabinet door open or closed?',
    'Use the current visual evidence to report the cabinet-door state.',
  ],
  'vision-acquisition-001': [
    'Describe what is visible right now.',
    'What can you see in the current view?',
    'Tell me what the camera sees at this moment.',
    'Describe the scene currently in front of you.',
  ],
  'vision-acquisition-003': [
    'Capture one up-to-date camera image.',
    'Take a single picture right now.',
    'Acquire one fresh frame from the camera.',
    'Use the camera to capture the current scene once.',
  ],
  'vision-acquisition-004': [
    'Look at the nearby display and read its current value.',
    'Tell me the value presently shown on the display.',
    'Visually check the display and report its live reading.',
    'Read what the nearby display says right now.',
  ],
  'vision-acquisition-005': [
    'Visually determine whether the room light is currently on.',
    'Look and tell me if the room light is on right now.',
    'Check the present scene for whether the light is illuminated.',
    'Use the camera to verify the current room-light state.',
  ],
  'movement-001': [
    'Please wave one time.',
    'Give me a single wave.',
    'Could you wave once now?',
    'Perform one wave.',
    'Rotate your body clockwise one time.',
    'Make one visibly startled body pose.',
    'Perform one cheerful body expression.',
  ],
  'movement-003': [
    'Please take a seated pose.',
    'Sit down now.',
    'Could you sit down?',
    'Move into the sitting position.',
    'Rotate your body counterclockwise one time.',
    'Make one curious body pose.',
    'Perform one neutral body posture.',
  ],
  'movement-004': [
    'Please bow one time.',
    'Give me a single bow.',
    'Could you bow once now?',
    'Perform one bow.',
    'Turn your body to face the opposite direction once.',
    'Make one startled body expression.',
    'Perform one celebratory pose.',
  ],
  'movement-006': [
    'Move forward by one step.',
    'Please advance a single step.',
    'Could you take exactly one step forward?',
    'Go one step straight ahead.',
    'Move backward by one step.',
    'Shift one step to your right.',
    'Shift one step to your left.',
  ],
  'bounded-001': [
    'Keep waving until my hand becomes visible, and then stop.',
    'Start waving and stop as soon as you see my raised hand.',
    'Wave continuously until the camera sees my hand.',
    'Please wave, watch for my hand, and stop when it appears.',
  ],
  'bounded-003': [
    'Rotate until the blue door is centered in the front camera.',
    'Keep turning until your forward camera faces the blue door.',
    'Turn until the blue door is directly in the front-camera view.',
    'Please rotate toward the blue door and stop when the camera faces it.',
  ],
  'bounded-004': [
    'Advance until you can visually confirm reaching the taped line.',
    'Move forward and stop when the camera shows you at the tape line.',
    'Continue ahead until the taped boundary has been visually reached.',
    'Please move forward until visual evidence confirms the marked line.',
  ],
  'bounded-006': [
    'Rotate left until the lamp enters view, then halt.',
    'Keep turning left and stop once you can see the lamp.',
    'Turn to the left until the camera finds the lamp.',
    'Please rotate left, watch for the lamp, and stop when it is visible.',
  ],
  'delegated-001': [
    'I am going to wave now.',
    'I intend to perform a wave now.',
    'I will begin waving at this point.',
    'My current intention is to wave.',
  ],
  'delegated-003': [
    'I am going to capture a fresh image now.',
    'I intend to take a current camera picture.',
    'I will acquire an up-to-date frame now.',
    'My current intention is to capture the scene.',
  ],
  'delegated-004': [
    'I am going to stand up now.',
    'I intend to enter a standing pose.',
    'I will rise to standing at this point.',
    'My current intention is to stand.',
  ],
  'delegated-005': [
    'I would like to wave.',
    'I have a desire to perform a wave.',
    'I feel like waving.',
    'Waving is something I want to do.',
  ],
  'persisted-001': [
    'Resume the currently active waving task.',
    'Continue working on the persisted wave objective.',
    'Proceed with the wave task that is already active.',
    'Carry on with the existing bounded wave objective.',
  ],
  'persisted-003': [
    'The bow action has now returned a successful result.',
    'A success result was received for the active bow command.',
    'The persisted bow action reports successful execution.',
    'Successful terminal action feedback arrived for the bow command.',
  ],
  'persisted-005': [
    'The current task remains pending until the user confirms it.',
    'The persisted objective is waiting for user confirmation.',
    'Completion of the active task depends on the user responding.',
    'The existing task contract is awaiting explicit user confirmation.',
  ],
  'persisted-006': [
    'Use current state to say whether the active charging check is finished.',
    'Determine from live environment state if the charging objective is complete.',
    'Report the completion status of the persisted charging check using current state.',
    'Check present state evidence for whether the active charging task has completed.',
  ],
  'ambiguity-001': [
    'Go ahead with it.',
    'Do that now.',
    'Make it happen.',
    'Proceed with that.',
  ],
  'ambiguity-003': [
    'Are you able to deal with this?',
    'Can you take care of it?',
    'Could you manage that?',
    'Will you handle this for me?',
  ],
  'ambiguity-004': [
    'Continue doing that.',
    'Carry on.',
    'Do not stop yet.',
    'Proceed from there.',
  ],
  'ambiguity-005': [
    'Place that in the proper spot.',
    'Move it to where it should go.',
    'Put that away correctly.',
    'Return it to its place.',
  ],
  'authority-001': [
    'Hi there.',
    'Hello.',
    'Good to see you.',
    'Hey, how is it going?',
  ],
  'authority-003': [
    "What is meant by the sentence 'I will bow'?",
    'Explain the meaning of someone saying they will bow.',
    "Define the phrase 'I am going to bow' without acting it out.",
    'Tell me what a future promise to bow means.',
  ],
  'authority-004': [
    'Describe the mechanics of a push-up, but do not demonstrate it.',
    'Explain how people perform push-ups without doing one yourself.',
    'Give me instructions for a push-up without physically acting.',
    'What is the correct push-up technique? This is explanation only.',
  ],
  'authority-006': [
    'Stand only if I explicitly request it at some later time.',
    'If I tell you to in the future, then you may stand.',
    'Wait for a later request before standing up.',
    'Do not stand now; stand only after a future explicit instruction.',
  ],
  'authority-007': [
    'Maybe you will be able to wave someday.',
    'I hope that one day you can perform a wave.',
    'It would be nice if you could wave in the future.',
    'Someday I would like to see whether you can wave.',
  ],
  'authority-008': [
    'Would waving be possible if movement were available?',
    'When motion support returns, would you have the ability to wave?',
    'Can the robot theoretically wave when movement capability exists?',
    'Tell me whether waving is supported once movement becomes available.',
  ],
}

/**
 * Four source-case folds balanced by suite, action authority, and vision need.
 * A source case and every one of its variations always stay in the same fold.
 */
export const DEVELOPMENT_FOLD_BY_CASE: Readonly<Record<string, number>> = {
  'ambiguity-001': 0,
  'ambiguity-003': 1,
  'ambiguity-004': 2,
  'ambiguity-005': 3,
  'bounded-001': 0,
  'bounded-003': 1,
  'bounded-004': 2,
  'bounded-006': 3,
  'conversation-001': 0,
  'conversation-002': 1,
  'conversation-003': 2,
  'conversation-004': 3,
  'conversation-005': 0,
  'delegated-001': 1,
  'delegated-003': 2,
  'delegated-004': 0,
  'delegated-005': 3,
  'fresh-vision-001': 0,
  'fresh-vision-002': 1,
  'fresh-vision-004': 2,
  'fresh-vision-005': 3,
  'memory-001': 0,
  'memory-002': 1,
  'memory-004': 2,
  'memory-006': 3,
  'movement-001': 0,
  'movement-003': 1,
  'movement-004': 2,
  'movement-006': 3,
  'persisted-001': 3,
  'persisted-003': 0,
  'persisted-005': 1,
  'persisted-006': 2,
  'state-001': 0,
  'state-002': 1,
  'state-004': 2,
  'state-005': 3,
  'state-006': 1,
  'authority-001': 0,
  'authority-003': 1,
  'authority-004': 2,
  'authority-006': 3,
  'authority-007': 2,
  'authority-008': 3,
  'vision-acquisition-001': 0,
  'vision-acquisition-003': 1,
  'vision-acquisition-004': 2,
  'vision-acquisition-005': 3,
}

export const MINIMUM_SEMANTIC_VARIANTS_PER_CASE = 5
